import Image from 'next/image';
import Link from 'next/link';
import { getBasicPriceARS } from '@/lib/billingConfig';

const schedule = [
  { time: '09:30', name: 'Corte + barba', client: 'Sofía R.', tone: 'confirmed' },
  { time: '11:00', name: 'Coloración', client: 'Marina P.', tone: 'pending' },
  { time: '14:30', name: 'Manicuría semipermanente', client: 'Luz M.', tone: 'confirmed' },
];

export default function LandingPage() {
  const basicPriceARS = getBasicPriceARS();
  return (
    <div className="landing-page">
      <header className="site-header">
        <Link className="brand" href="/" aria-label="FezTime, inicio"><Image src="/feztime-logo.svg" alt="" width={34} height={34} priority /><span>FezTime</span></Link>
        <nav className="header-actions" aria-label="Navegación principal"><Link className="header-demo" href="/demo">Ver demo</Link><Link className="header-login" href="/login">Ingresar</Link><Link className="button button-small" href="/register">Crear cuenta</Link></nav>
      </header>
      <main>
         <section className="hero section-shell"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Agenda online para servicios profesionales</p><h1>Más turnos. Menos mensajes pendientes.</h1><p className="hero-lede">FezTime ordena tus reservas, horarios y clientes en un solo lugar para que tu negocio se vea tan profesional como el servicio que ofrecés.</p><div className="hero-actions"><Link className="button" id="cta" href="/register">Probar gratis 14 días <span aria-hidden="true">→</span></Link><Link className="text-link" href="#como-funciona">Conocé cómo funciona <span aria-hidden="true">↓</span></Link></div><p className="microcopy">Publicá tu agenda y empezá a compartirla.</p></div><ProductPreview /></section>
        <section className="trust-strip" aria-label="Para quién es FezTime"><div className="section-shell trust-inner"><span>Una agenda clara para negocios que trabajan con turnos</span><div className="trust-items"><span>Barberías</span><span>Peluquerías</span><span>Manicuristas</span><span>Estética</span></div></div></section>
        <section className="outcomes section-shell" id="beneficios"><div className="section-intro"><p className="eyebrow">El trabajo de todos los días</p><h2>Tu negocio, con espacio para crecer.</h2><p>La agenda no debería ser otro problema que resolver. FezTime reúne lo esencial para trabajar con más orden y transmitir confianza desde el primer contacto.</p></div><div className="outcome-grid"><Outcome number="01" title="Reservas sin ida y vuelta" text="Compartí un link y dejá que tus clientes elijan un servicio, un día y un horario disponible." /><Outcome number="02" title="Una vista para tu día" text="Consultá tu agenda y el estado de cada turno sin buscar conversaciones viejas." /><Outcome number="03" title="Una experiencia más profesional" text="Tu negocio tiene un espacio propio para recibir reservas, con horarios y servicios claros." /></div></section>
        <section className="steps-section" id="como-funciona"><div className="section-shell"><div className="section-intro"><p className="eyebrow">Empezá en minutos</p><h2>De la agenda desordenada a un link compartible.</h2></div><div className="steps-grid"><Step number="1" title="Creá tu cuenta" text="Registrate y completá los datos básicos de tu negocio." /><Step number="2" title="Cargá tu propuesta" text="Definí tus servicios, duración y horarios de atención." /><Step number="3" title="Compartí tu agenda" text="Publicá tu link en WhatsApp, Instagram o donde te encuentren." /></div></div></section>
        <section className="proof section-shell"><div className="proof-card"><div><p className="eyebrow">Hecho para mostrar el trabajo real</p><h2>La primera impresión también se agenda.</h2><p>Sin promesas infladas ni métricas de catálogo. FezTime te da una experiencia de reserva concreta, fácil de entender y lista para compartir.</p></div><Link className="text-link light-link" href="/demo">Explorar la demo <span aria-hidden="true">→</span></Link></div></section>
         <section className="pricing section-shell" id="pricing"><div className="pricing-copy"><p className="eyebrow">Prueba y precio claros</p><h2>Probalo con tu negocio antes de decidir.</h2><p>Empezá con 14 días de prueba. Si decidís continuar, el plan básico cuesta <strong>${basicPriceARS.toLocaleString('es-AR')} ARS por mes</strong>.</p></div><div className="price-card"><p className="price-label">Plan básico</p><p className="price"><span>${basicPriceARS.toLocaleString('es-AR')}</span> ARS <small>/ mes</small></p><p className="price-note">Después de tu prueba de 14 días</p><ul><li>Agenda online para compartir</li><li>Servicios y horarios configurables</li><li>Gestión de turnos y clientes</li></ul><Link className="button button-wide" href="/register">Empezar prueba gratuita <span aria-hidden="true">→</span></Link></div></section>
        <section className="final-cta section-shell"><p className="eyebrow">Tu próximo turno empieza acá</p><h2>Ordená tu agenda. Atendé mejor.</h2><p>FezTime te ayuda a convertir consultas en reservas sin sumar trabajo administrativo.</p><Link className="button" href="/register">Crear mi agenda <span aria-hidden="true">→</span></Link></section>
      </main>
      <footer className="site-footer"><div className="section-shell footer-inner"><div><Link className="brand" href="/"><Image src="/feztime-logo.svg" alt="" width={28} height={28} /><span>FezTime</span></Link><p>Agenda online para negocios de servicios.</p></div><div className="footer-links"><Link href="/terms">Términos</Link><Link href="/privacy">Privacidad</Link><Link href="/login">Ingresar</Link></div><p className="copyright">© {new Date().getFullYear()} FezTime.</p></div></footer>
    </div>
  );
}

function ProductPreview() {
  return <div className="product-preview" aria-label="Vista previa de la agenda pública y la agenda del negocio"><div className="preview-topline"><span className="preview-dot" /> Vista previa del producto <span>feztime.app/tu-negocio</span></div><div className="preview-panels"><div className="booking-panel"><div className="mini-brand"><span className="mini-mark">F</span><span>Estudio Norte</span></div><p className="preview-kicker">Reservá tu turno</p><h3>Elegí un servicio</h3><div className="service-choice active"><span><strong>Corte + barba</strong><small>45 min</small></span><b>$8.000</b></div><div className="service-choice"><span><strong>Coloración</strong><small>90 min</small></span><b>$15.000</b></div><div className="date-row"><span>‹</span><strong>JULIO 2026</strong><span>›</span></div><div className="days"><span>L<br /><b>20</b></span><span className="selected">M<br /><b>21</b></span><span>X<br /><b>22</b></span><span>J<br /><b>23</b></span><span>V<br /><b>24</b></span></div><div className="time-row"><span>09:30</span><span>11:00</span><span>14:30</span></div><span className="preview-button" aria-hidden="true">Continuar</span></div><div className="agenda-panel"><div className="agenda-heading"><div><small>MIÉRCOLES 22 DE JULIO</small><h3>Agenda del día</h3></div><span className="agenda-add">+</span></div>{schedule.map((item) => <div className="agenda-line" key={item.time}><span>{item.time}</span><div className={`appointment ${item.tone}`}><strong>{item.time} · {item.client}</strong><small>{item.name} · {item.tone === 'confirmed' ? 'Confirmado' : 'Pendiente'}</small></div></div>)}</div></div></div>;
}

function Outcome({ number, title, text }: { number: string; title: string; text: string }) { return <article className="outcome"><span className="outcome-number">{number}</span><h3>{title}</h3><p>{text}</p></article>; }
function Step({ number, title, text }: { number: string; title: string; text: string }) { return <article className="step"><span className="step-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></article>; }
