'use client';

import { useEffect, useMemo, useState } from 'react';

type BillingInfo = { planName: string; status: string; statusCode: string; paidUntil: string | null; priceARS: number; billingMode?: 'manual' | 'auto' | null };
type Payment = { id: string; status: 'approved' | 'pending' | 'rejected'; createdAt: string; amount: number; currency: string; providerReference: string; paidThrough: string };

export default function BillingClient({ billingInfo }: { billingInfo: BillingInfo }) {
  const [manualLoading, setManualLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [payments, setPayments] = useState<Payment[]>([]); const [historyLoading, setHistoryLoading] = useState(true); const [reconciling, setReconciling] = useState<string | null>(null);
  async function loadHistory() { setHistoryLoading(true); try { const res = await fetch('/api/billing/history?limit=20'); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'No se pudo cargar el historial'); setPayments(data.payments || []); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo cargar el historial'); } finally { setHistoryLoading(false); } }
  useEffect(() => { void loadHistory(); }, []);
  async function reconcile(paymentId: string) { setReconciling(paymentId); setError(null); try { const res = await fetch('/api/billing/reconcile', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paymentId }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'No se pudo actualizar el pago'); await loadHistory(); } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo actualizar el pago'); } finally { setReconciling(null); } }
  const paidUntilLabel = useMemo(() => billingInfo.paidUntil ? new Date(billingInfo.paidUntil).toLocaleDateString('es-AR') : 'Sin pagos registrados', [billingInfo.paidUntil]);
  const isActive = billingInfo.statusCode === 'active' || billingInfo.statusCode === 'trial';
  const statusDescription = isActive ? 'El panel está disponible.' : billingInfo.statusCode === 'past_due' ? 'El acceso operativo está pausado. Podés recuperar el plan desde acá.' : billingInfo.statusCode === 'expired' ? 'Acceso vencido. Renovalo desde acá para recuperar el panel.' : 'La facturación sigue disponible para revisar o recuperar el acceso.';
  async function handleManualPay() { setManualLoading(true); setError(null); try { const res = await fetch('/api/billing/mp/checkout', { method: 'POST' }); if (!res.ok) throw new Error('No se pudo crear el pago'); const data = await res.json(); if (!data.initPoint) throw new Error('No se recibió el link de pago'); window.location.href = data.initPoint; } catch (err) { setError(err instanceof Error ? err.message : 'No se pudo iniciar el pago.'); setManualLoading(false); } }

  return <div className="space-y-6">
    <section className="grid gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-[0_16px_50px_rgba(15,23,42,0.07)] sm:grid-cols-[1fr_auto] sm:p-8">
      <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">Plan actual</p><div className="mt-3 flex flex-wrap items-center gap-3"><h2 className="font-serif text-3xl tracking-[-0.03em]">{billingInfo.planName}</h2><span className="rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1 text-xs font-medium text-indigo-800">Turnos ilimitados · 1 local</span></div><p className="mt-5 text-sm text-slate-600">Pagado hasta <strong className="text-slate-950">{paidUntilLabel}</strong></p></div>
      <div className="rounded-2xl border border-slate-200 bg-[#f7f5f0] p-4 sm:min-w-44 sm:text-right"><p className="text-xs text-slate-500">Estado de la cuenta</p><p className="mt-2 flex items-center gap-2 font-semibold sm:justify-end"><span aria-hidden="true" className={`h-2.5 w-2.5 rounded-full ${isActive ? 'bg-emerald-600' : 'bg-amber-600'}`} />{billingInfo.status}</p><p className="mt-2 max-w-48 text-xs leading-5 text-slate-600 sm:ml-auto">{statusDescription}</p></div>
    </section>
    {error && <div role="alert" className="rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm leading-6 text-red-900">{error}<p className="mt-1 text-xs text-red-800/80">No compartas contraseñas, tokens ni datos de tarjeta con soporte.</p></div>}
    <section className="grid gap-6 lg:grid-cols-[1fr_1.2fr]">
      <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-indigo-700">Renovar cuando lo necesites</p><h2 className="mt-3 font-serif text-2xl tracking-[-0.03em]">${billingInfo.priceARS.toLocaleString('es-AR')} <span className="font-sans text-sm font-normal tracking-normal text-slate-500">ARS / mes</span></h2><p className="mt-3 text-sm leading-6 text-slate-600">Hacés un pago manual cuando querés renovar. No hay débito automático ni cobros programados.</p><button onClick={handleManualPay} disabled={manualLoading} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-700 px-4 py-3 text-sm font-semibold text-white transition hover:bg-indigo-800 disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2">{manualLoading && <span aria-hidden="true" className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />}{manualLoading ? 'Preparando pago...' : 'Pagar este mes'}</button><p className="mt-3 text-center text-xs text-slate-500">Al continuar, te llevamos al sitio seguro de Mercado Pago.</p></div>
      <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="font-serif text-2xl tracking-[-0.03em]">Historial de pagos</h2><p className="mt-2 text-sm leading-6 text-slate-600">Referencias para entender el estado y pedir ayuda, sin datos de tarjeta.</p></div><button onClick={() => void loadHistory()} className="shrink-0 rounded-lg px-2 py-1 text-sm font-medium text-indigo-700 underline-offset-4 hover:bg-indigo-50 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Actualizar</button></div>
        {historyLoading ? <p className="mt-6 text-sm text-slate-500" role="status">Cargando pagos...</p> : payments.length === 0 ? <p className="mt-6 rounded-2xl border border-dashed border-slate-300 bg-slate-50 px-4 py-5 text-sm leading-6 text-slate-600">Todavía no hay pagos registrados. Cuando hagas uno, su referencia y estado van a aparecer acá.</p> : <div className="mt-6 space-y-3">{payments.map((payment) => { const label = payment.status === 'approved' ? 'Aprobado' : payment.status === 'pending' ? 'Pendiente' : 'Rechazado o cancelado'; const tone = payment.status === 'approved' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : payment.status === 'pending' ? 'border-amber-200 bg-amber-50 text-amber-950' : 'border-red-200 bg-red-50 text-red-900'; return <div key={payment.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-slate-900">{label} · {payment.amount.toLocaleString('es-AR')} {payment.currency}</p><p className="mt-1 text-xs text-slate-500">{new Date(payment.createdAt).toLocaleDateString('es-AR')} · Referencia {payment.providerReference}</p></div><span className={`self-start rounded-full border px-3 py-1 text-xs font-medium ${tone}`}>{payment.status === 'approved' ? `Cubre hasta ${new Date(payment.paidThrough).toLocaleDateString('es-AR')}` : 'Revisá el estado'}</span></div>{payment.status !== 'approved' && <div className="mt-3 border-t border-slate-100 pt-3"><p className="text-xs leading-5 text-slate-600">Si ya pagaste, verificá esta referencia una vez. Si sigue pendiente o rechazado, contactá soporte con la referencia, no con datos privados.</p><button onClick={() => void reconcile(payment.providerReference)} disabled={reconciling === payment.providerReference} className="mt-2 rounded-lg text-sm font-semibold text-indigo-700 underline-offset-4 hover:underline disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">{reconciling === payment.providerReference ? 'Verificando...' : 'Verificar pago'}</button></div>}</div>; })}</div>}
      </section>
    </section>
  </div>;
}
